name: CI + CD

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ben-poole/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Check previous env sha
        id: check-previous-env-sha
        run: |
          export AWS_DEFAULT_REGION=eu-west-1
          paramName="current-sha-int-PLAN"
          echo "param to check is: '$paramName'"
          if [ $paramName != "" ]; then
            echo "checking param store for sha '$paramName'"
            echo "aws ssm get-parameters --names $paramName"
            aws ssm get-parameters --names $paramName --debug
            ssm=$(aws ssm get-parameters --names "${paramName}")
            sha=$(echo $ssm | jq --arg pn "${paramName}" -r '.Parameters[] | select(.Name == $pn) | .Value')
            echo "sha from param store is: ${sha}"
          fi
        
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
