name: Reusable Workflows Example

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ben-poole/gha-environments/.github/workflows/reusable-workflow-1-deploy.yml@main
    with:
      AWS_DEFAULT_REGION: eu-west-1
      environment: Development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  output1:
    runs-on: ubuntu-latest
    needs: [ deploy-dev ]
    steps:
      - run: echo ${{ needs.deploy-dev.outputs.output1 }}

  deploy-staging:
    needs: [ deploy-dev ]
    uses: ben-poole/gha-environments/.github/workflows/reusable-workflow-1-deploy.yml@main
    with:
      AWS_DEFAULT_REGION: eu-west-1
      environment: Staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
