name: RW1 - Deploy

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    timeout-minutes: 10
    env:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Deploy
        id: deploy
        run: echo I am deploying! ${{ inputs.AWS_DEFAULT_REGION }} ENV_SECRET ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: Sts
        id: sts
        run: aws sts get-caller-identity
        