name: RW1 - Deploy

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Deploy
        id: deploy
        run: echo I am deploying! ${{ inputs.username }}  ${{ secrets.ENV_SECRET }}
        