name: Trigger another workflow

on:
  workflow_dispatch:
  
jobs:
  trigger-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run hello.yml --repo ben-poole/github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
