name: Trigger another workflow

on:
  workflow_dispatch:
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run hello.yml --repo ben-poole/github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
