name: Without Environments reusable

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: "The deployment action"
        required: true
        options: 
        - PLAN-int
        - DEPLOY-int
        - PLAN-uat
        - DEPLOY-uat
        - PLAN-prod
        - DEPLOY-prod

concurrency:
  group: deploy

jobs:
  _0_build:
    name: 0. Build, Audit, Test & Package
    runs-on: ubuntu-latest
    env:
      LAMBDA_S3_BUCKET_NAME: "gha-envs-example-artifacts"
    timeout-minutes: 5
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          persist-credentials: false

      - name: Extract info
        run: |
          echo "##[set-output name=sha;]$(git log --oneline --format=format:%h -- . | head -1)"
        id: extract_info

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Build
        run: |
          echo "Building"
          #echo "//npm.pkg.github.com/:_authToken=${{ secrets.CUSTOM_PAT }}" >> ~/.npmrc
          #echo "@ben-poole:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          #rm -rf ./node_modules/ && rm -rf ./dist/
          #npm run clean
          #npm ci
          #npm run build

      #- name: Audit
      #  run: |
      #    @todo npm/yarn audit

      #- name: Test
      #  run: |
      #    npx jest
      #    echo "Exited with '$?'"

      - name: Package
        run: |
          echo "Packaging lambdas etc"
          #npm prune --production
          #cp -r node_modules dist/
          #cd dist/
          #zip ../my-lambda-${{ steps.extract_info.outputs.sha }}.zip * -r
          #cd ../
          #rm -rf dist/

      - name: Upload 
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
          #AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_USER_AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_USER_AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Uploading lambdas to S3 and images to ECR"
          #aws s3 cp my-lambda-${{ steps.extract_info.outputs.sha }}.zip s3://${{ env.LAMBDA_S3_BUCKET_NAME }}/${{ github.event.repository.name }}/my-lambda-${{ steps.extract_info.outputs.sha }}.zip

    outputs:
      lambda_s3_bucket_name: "${{ env.LAMBDA_S3_BUCKET_NAME }}"
      lambda_s3_bucket_path: "${{ github.event.repository.name }}/my-lambda-${{ steps.extract_info.outputs.sha }}.zip"
    
  _1_int_plan:
    needs: [ _0_build ]
    name: 1. Plan on INT
    uses: ben-poole/gha-environments/.github/workflows/reusable-workflow-example-3-terraform.yml@main
    with:
      TERRAFORM_ENVIRONMENT: int
      TERRAFORM_ACTION: PLAN
      WORKFLOW_TERRAFORM_ACTION: "${{ github.event.inputs.action }}"
      # These vars are the same for all jobs
      TF_VAR_lambda_s3_bucket_name: "${{ needs._0_build.outputs.lambda_s3_bucket_name }}"
      TF_VAR_lambda_s3_bucket_path: "${{ needs._0_build.outputs.lambda_s3_bucket_path }}"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}

  _2_int_deploy:
    name: 2. Deploy on INT
    needs: [ _0_build, _1_int_plan ]
    if: needs._1_int_plan.outputs.action_run != 'true'
    uses: ben-poole/gha-environments/.github/workflows/reusable-workflow-example-3-terraform.yml@main
    with:
      TERRAFORM_ENVIRONMENT: int
      TERRAFORM_ACTION: APPLY
      WORKFLOW_TERRAFORM_ACTION: "${{ github.event.inputs.action }}"
      # These vars are the same for all jobs
      TF_VAR_lambda_s3_bucket_name: "${{ needs._0_build.outputs.lambda_s3_bucket_name }}"
      TF_VAR_lambda_s3_bucket_path: "${{ needs._0_build.outputs.lambda_s3_bucket_path }}"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
